### ISSUE TITLE
background gene set for enrichMesh isn't working

### ISSUE THREAD

**Issue by ymkng** [GuangchuangYu/meshes#2]
I was wondering what "universe" for enrichMesh function accepts as an input as it isn't specified in the documentation found on bioconductor. 

```{R}
library(meshes)
x <- enrichMeSH(my.geneID3[,3], MeSHDb = "MeSH.Hsa.eg.db", database='gene2pubmed', category = 'C',universe = univ.geneID3[,2])
```
here, univ.geneID3[,2]  is a list of entrez gene ids but I get the error

Error in validObject(.Object) : 
  invalid class "enrichResult" object: invalid object for slot "universe" in class "enrichResult": got class "integer", should be or extend class "character"

thanks so much! 

michelle

**Comment by GuangchuangYu** [comment]
>got class "integer", should be or extend class "character"

```
as.character(univ.geneID3[,2])
```

will solve this issue. Gene ID should be in character.

**Comment by ymkng** [comment]
thanks so much!
